# Generated by Django 3.0.5 on 2021-01-05 23:33

import ShopBotAPI.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeID', models.IntegerField()),
                ('storeName', models.CharField(max_length=100)),
                ('storeAddress', models.CharField(max_length=100)),
                ('storePassword', models.CharField(max_length=100)),
                ('storeProducts', djongo.models.fields.ArrayField(model_container=ShopBotAPI.models.Products)),
                ('storeOrders', djongo.models.fields.ArrayField(model_container=ShopBotAPI.models.Orders)),
                ('storeEmployees', djongo.models.fields.ArrayField(model_container=ShopBotAPI.models.Employees)),
            ],
        ),
        migrations.CreateModel(
            name='ShopBotUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userFirstName', models.CharField(max_length=100)),
                ('userLastName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=100)),
                ('userOrder', djongo.models.fields.ArrayField(model_container=ShopBotAPI.models.Orders)),
            ],
        ),
    ]
