# Generated by Django 2.2.17 on 2021-02-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('store_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ShopBotAPI.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='StoreListings',
            fields=[
                ('listing_ID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_details', to='ShopBotAPI.ProductDetails')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ShopBotAPI.GroceryStore')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('item_count', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('completed', models.BooleanField(default=False)),
                ('store_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_details', to='ShopBotAPI.GroceryStore')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('wanted_num', models.IntegerField()),
                ('listing_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_details', to='ShopBotAPI.StoreListings')),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_list', to='ShopBotAPI.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_working', models.BooleanField(default=False)),
                ('store_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employed_store', to='ShopBotAPI.GroceryStore')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
