export const USER_LOADING = "USER_LOADING";

export const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_LOG_IN_FAIL = "USER_LOG_IN_FAIL";

export const GROCERY_USER_LOADED = "GROCERY_USER_LOADED";
export const GROCERY_AUTH_ERROR = "GROCERY_AUTH_ERROR";
export const GROCERY_LOG_IN_SUCCESS = "GROCERY_LOG_IN_SUCCESS";
export const GROCERY_LOG_IN_FAIL = "GROCERY_LOG_IN_FAIL";

export const USER_LOG_OUT = "USER_LOG_OUT";

export const ADDED_TO_CART = "ADDED_TO_CART";
export const SEARCH_ZIP = "SEARCH_ZIP";
export const SELECT_STORE = "SELECT_STORE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";