export const USER_LOADING = "USER_LOADING";
export const GROCERY_USER_LOADED = "GROCERY_USER_LOADED";
export const GROCERY_AUTH_ERROR = "GROCERY_AUTH_ERROR";
export const GROCERY_LOG_IN_SUCCESS = "GROCERY_LOG_IN_SUCCESS";
export const GROCERY_LOG_IN_FAIL = "GROCERY_LOG_IN_FAIL";
export const USER_LOG_OUT = "USER_LOG_OUT";